#
#  ____  ____ _____         _
# |  _ \/ ___|_   _|_ _ ___| | __
# | |_) \___ \ | |/ _` / __| |/ /
# |  _ < ___) || | (_| \__ \   <
# |_| \_\____/ |_|\__,_|___/_|\_\
#
# @author 若水
# 请不要随意更改配置， 否则会出现无法加载BUG
# 以下可以自定义按键名称与路径 按键数量为任务难度

#配置文件版本 跟插件版本不挂钩
version: "1.5.1"

#作用于任务分组
自定义图片路径:
 "0":
  名称: "§7[§a主线§7]§b 第一章"
  图片类型: "本地"
  图片路径: "textures/ui/filledStarFocus"
  解锁积分: 0
 "1":
  名称: "§7[§a主线§7]§b 第二章"
  图片类型: "本地"
  图片路径: "textures/ui/icon_deals"
  解锁积分: 100
 "2":
  名称: "§7[§a主线§7]§b 第三章"
  图片类型: "本地"
  图片路径: "textures/ui/icon_best3"
  解锁积分: 200
 "3":
  名称: "§7[§a主线§7]§b 第四章"
  图片类型: "本地"
  图片路径: "textures/ui/icon_armor"
  解锁积分: 300
 "4":
  名称: "§7[§a主线§7]§b 第五章"
  图片类型: "本地"
  图片路径: "textures/ui/icon_balloon"
  解锁积分: 400
 "5":
  名称: "§7[§c支线§7]§b 支线任务"
  图片类型: "本地"
  图片路径: "textures/ui/icon_blackfriday"
  解锁积分: 0
 "6":
  名称: "§7[§b日常§7]§b 日常任务"
  图片类型: "本地"
  图片路径: "textures/ui/icon_book_writable"
  解锁积分: 300

#是否开启积分验证 如果开启则判断任务积分是否足以解锁下一级别任务 反之不检测
是否开启积分验证: true


#初始级别分数(建议为0)
初始级别分数: 0

#排行榜显示玩家数量 （如果积分验证为关闭状态）
# 则无法使用排行榜功能
排行榜显示玩家数量: 10

金币名称: "§e金币§r"

积分名称: "§b积分§r"

#是否使用经济功能
enable-Economy: true

#当玩家正在进行任务时 在底部显示百分比
是否在底部显示任务进度: true

#关闭此选项后点击任务后将删除返回按键
是否增加任务界面返回按钮: true

#关闭此选项后玩家将无法执行/c
是否允许玩家执行c指令: true

#显示任务进度的底部类型 分为popup,tip,action
底部显示类型: "tip"


# 显示数量后将会在每个等级后均有每个任务状态的数量显示
# 但是这样会导致打开任务菜单卡顿
主页面是否显示数量: true

# 可以放心了，自带书本检测
领取任务是否给予任务书: false

完成任务是否直接领取奖励: false

# 支持 EconomyAPI Money ,PlayerPoint
使用经济核心: EconomyAPI



